two_handles/two_handles_blog/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :projects
  get 'welcome/index'
  root 'welcome#index'
end

two_handles/two_handles_blog/app/models/post.rb
class Post < ActiveRecord::Base
end

two_handles/two_handles_blog/app/models/project.rb
class Project < ActiveRecord::Base
end

two_handles/two_handles_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

two_handles/two_handles_blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: " Your article is saved!"
    else
      render 'new', notice: "Oh, no. It didn't save."
    end
  end

  def show
#    @post = Post.find(params[:id])
  end

  def edit
  end



  def update
    if @post.update post_params
      redirect_to @post, notice: "Great!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end


  private
  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

two_handles/two_handles_blog/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all.order("created_at desc")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params

    if @project.save
      redirect_to @project, notice: "Nice job! Now it's saved."
    else
      render 'new'
    end
  end

  private

  def project_params
    parms.require(:project).permit(:title, :description,
    :link)
  end


end

two_handles/two_handles_blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.limit(3).order("created_at desc")
  end

end

two_handles/two_handles_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

two_handles/two_handles_blog/app/helpers/posts_helper.rb
module PostsHelper
end

two_handles/two_handles_blog/app/helpers/projects_helper.rb
module ProjectsHelper
end

two_handles/two_handles_blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

two_handles/two_handles_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <head>
    <title>Andrew Overby - Two Handles Blog</title>
    <link href="//fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="//path/to/font-awesome/css/font-awesome.min.css">
  </head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="main_navigation" class="clearfix">
    <%= link_to "#MY NAME", root_path, class: "name" %>
    <a href="#" class="name">Andrew Overby</a>
    <nav>
      <% link_to "Articles", posts_path %>
      <a href="#">Projects</a>
      <a href="#">Contact</a>
    </nav>
  </header>

<%= yield %>

<footer id="main_footer">
  <nav>
  <p class="copyright">&copy; 2016 Andrew Overby</p>
  <a href="https://www.linkedin.com/in/andrewdoverby" target="_blank">
    <i class="fa fa-linkedin"></i></a>
  <a href="#" target="_blank"><i class="fa fa-degreed"></i></a>
  <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
  </nav>
  <nav>
  <a href="#">LinkedIn</a>
  <a href="#">Degreed</a>
  <a href="#">Twitter</a>
  </nav>

</footer>


</body>
</html>

two_handles/two_handles_blog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %> </l>
    <% end %>
  </ul>
<% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :content, "Write your article here" %><br>
  <%= f.text_area :content %>

  <br>
  <br>

  <% f.submit %>


<% end %>

two_handles/two_handles_blog/app/views/posts/edit.html.erb
<h1> Edit Post</h1>

<%= render 'form' %>

two_handles/two_handles_blog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

two_handles/two_handles_blog/app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper
wrapper_padding">
  <header>
    <p class="date"><%= @post.created_at.strftime('%A, %B, %d') %></p>
    <h1><%= @post.title %></h1>
    <hr>
  </header>
</div>

<div id="content">
  <%= @post.content %>
  <%#<h2>Narwhal sustainable</h2>
  <p>The refinancing of a primary residence when interest rates decline
    will include the added expense of closing costs.
    However, you can calculate the time period to
    break even with the additional refinancing costs
    (the time period before the actual savings benefits begin).
  </p>
%>
</div>
  <hr>

<div id="share_box">
  <p>Share the DO List</p>
  <!-- Twitter -->
  <a onclick="javascript:window.open('https://twitter.com/share?
  text=<%= @post.title %> by@overbyonline - &amp;url=<%= url_for([@post,
  {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200,
  left=300');void(0);"><i class="fa fa-twitter"></i></a>

  <!-- maybe Medium; which do I want to use? -->
  <!--<a onclick="javascript:window.open('https://twitter.com/share?
    text=<%= @post.title %> by@overbyonline - &amp;url=<%= url_for([@post,
    {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200,
    left=300');void(0);">"><i class="fa fa-medium"></i></a>
  -->

  <!-- LinkedIn here    https://www.linkedin.com/in/andrewdoverby
  <a onclick="javascript:window.open('https://twitter.com/share?
  text=<%= @post.title %> by@overbyonline - &amp;url=<%= url_for([@post,
  {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200,
  left=300');void(0);""><i class="fa fa-linkedin"></i></a>
-->
  <hr>

</div>

<% @post.title %>
<% @post.content %>

<br>
<br>






 link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete,
data: {confirm: "Are you sure you want to delete this post?"}

two_handles/two_handles_blog/app/views/projects/index.html.erb
<h1 id="page_title">Stuff I've Built</h1>

<div id="posts_wrapper" class="skinny_wrapper">
  <% @projects.each do |project| %>
  <div class="post">
    <p class="date"><%= project.created_at.strftime
    ('%A, %B, %d') %></p>
    <h2><a href="#"><%= link_to project.title,
    project %></a></h2>
    <hr>
  </div>
  <% end %>
</div>

two_handles/two_handles_blog/app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Andrew Overby - Here I am</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="https://path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/application.css">
  </head>
  <body>
    <header id="main_navigation" class="clearfix">
      <a href="#" class="name">Andrew Overby</a>
      <nav>
        <a href="articles.html">Articles</a>
        <a href="#">Projects</a>
        <a href="#">Contact</a>

    </header>

    <div class="wrapper  wrapper_padding clearfix">
      <div class="col-1 about homepage_content">
        <h2>About</h2>
        <hr>
        <p>I'm an aspiring financial planner, investor, grower of food, and thinker. </p>
      </div>

      <div class="col-2 homepage_content">
        <h2> Some Stuff I've Written</h2>
        <hr>

        <% @posts.each do |post| %>
        <h3><a href="#"><%= link_to, post.title, path %></a></h3>
        <p class="date"><%= post.created_at.strftime("%A, %b, %d") %></p>
        <% end %>

        <h3>The WRITE List</h3>
        <p class="date">Monday, September 26th</p>
        <h3>How do I learn "X"?</h3>
        <p class="date">Wednesday, September 28th</p>
        <h3>Strive for the uncomfortable</p>
        <p class="date">Friday, September 30th</p>
      </div>

      <div class="col-3 homepage_content">
        <h2> Some Stuff I've Built</h2>
        <hr>
        <h3><a href="#">The DO List</a></h3>
        <p class="date">Monday, September 26th</p>
        <h3>A Thing I Have Done</h3>
        <p class="date">Wednesday, September 28th</p>
        <h3>Something in the works</p>
        <p class="date">Friday, September 30th</p>
        </div>
      </div>

      <footer id="main_footer">
        <nav>
        <p class="copyright">&copy; 2016 Andrew Overby</p>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-degreed"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        </nav>
        <nav>
        <a href="#">LinkedIn</a>
        <a href="#">Degreed</a>
        <a href="#">Twitter</a>
        </nav>

      </footer>


  </body>

</html>